version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - redis-network

    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '8081:8081'
    networks:
      - redis-network
    depends_on:
      - redis

networks:
  redis-network:
    driver: bridge

volumes:
  redis_data:
